services:
  - type: web
    name: restaurant-backend
    runtime: node
    plan: free
    repo: https://github.com/korchi1an/RestaurantManager
    branch: main
    rootDir: ./backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_PATH
        value: ./restaurant.db
      - key: LOG_LEVEL
        value: info
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://restaurant-frontend-85q6.onrender.com

  - type: web
    name: restaurant-frontend
    runtime: static
    repo: https://github.com/korchi1an/RestaurantManager
    branch: main
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://restaurant-backend-85q6.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
